name: GLT CD

on:
  push:
    tags:
      - '*'

env:
  IMAGE: graphlearn-torch-wheel
  JOBNAME: glt-cd-${{ github.run_id }}
  DESTDIR: /mnt/graphlearn_for_pytorch

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.repository == 'alibaba/graphlearn-for-pytorch' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update submodules
        working-directory: ${{github.workspace}}
        run: |
          git submodule update --init
          
      - name: Build image
        working-directory: ${{github.workspace}}
        run: |
          docker build -f dockerfiles/${IMAGE}.Dockerfile -t ${IMAGE} .

      - name: Launch CD container
        working-directory: ${{github.workspace}}
        run: |
          bash scripts/launch_container.sh ${IMAGE} ${JOBNAME} ${DESTDIR}

      - name: Build python packages
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          docker exec ${JOBNAME} bash ${DESTDIR}/.github/workflows/scripts/build.sh ${GITHUB_REF}

      - name: Upload python packages
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        env:
          PYPI_PWD: ${{ secrets.PYPI_PWD }}
        run: |
          bash .github/workflows/scripts/upload_pypi.sh

      - name: Remove CD container
        if: always()
        working-directory: ${{github.workspace}}
        run: |
          bash scripts/remove_container.sh ${JOBNAME}
